### ISSUE TITLE
Error: AxiosError: Request failed with status code 400

### ISSUE THREAD

**Issue by bhavinatharva** [rnkdsh/action-upload-diawi#32] opened 2023-05-16 10:33 UTC
Failed:  Error: AxiosError: Request failed with status code 400
    at Diawi.execute (/home/runner/work/_actions/rnkdsh/action-upload-diawi/v1.3.0/diawi.js:65:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: AxiosError: Request failed with status code 400

**Comment by rnkdsh** [comment] 2023-05-26 11:06
I am unable to reproduce this issue. Please try the latest version to check whether it's still happening or not. Closing the issue.

**Closed by rnkdsh** 2023-05-26 11:06 UTC

**Comment by bhavinatharva** [comment] 2023-05-26 11:07
Hello @rnkdsh 

While uploading android apk file its returning this kind of issue

**Comment by rnkdsh** [comment] 2023-05-26 11:10
Will you please check whether the APK `file` path you are providing to the action is correct or not?

**Comment by bhavinatharva** [comment] 2023-05-29 05:20
it may around 90mb up file

**Comment by bhavinatharva** [comment] 2023-06-06 13:22
Hello @rnkdsh 

```
- name: Check if app-release.apk exists
        run: |
          if [ -f ${{ steps.download.outputs.download-path }}/app-release.apk ]; then
            echo "File exists"
          else
            echo "File does not exist"
            exit 1
          fi
      - name: Show File Size
        run: |
          file_path="${{ steps.download.outputs.download-path }}/app-release.apk"
          file_size=$(wc -c < "$file_path")
          echo "File size of $file_path is $file_size bytes"
          
      - name: Upload Diawi
        uses: rnkdsh/action-upload-diawi@v1.5.0
        with:
          token: ${{ secrets.DIAWI_TOKEN }}
          file: ${{ steps.download.outputs.download-path }}/app-release.apk
```


<img width="1057" alt="Screenshot 2023-06-06 at 6 52 03 PM" src="https://github.com/rnkdsh/action-upload-diawi/assets/84075780/883d2687-1c72-46da-a71f-2b800ed287e3">

**Comment by rizki-tabist** [comment] 2023-06-14 07:18
any update regarding this issue? and why is it closed?

**Comment by nakshatrasinghh** [comment] 2023-11-28 16:10
> Hello @rnkdsh
> 
> ```
> - name: Check if app-release.apk exists
>         run: |
>           if [ -f ${{ steps.download.outputs.download-path }}/app-release.apk ]; then
>             echo "File exists"
>           else
>             echo "File does not exist"
>             exit 1
>           fi
>       - name: Show File Size
>         run: |
>           file_path="${{ steps.download.outputs.download-path }}/app-release.apk"
>           file_size=$(wc -c < "$file_path")
>           echo "File size of $file_path is $file_size bytes"
>           
>       - name: Upload Diawi
>         uses: rnkdsh/action-upload-diawi@v1.5.0
>         with:
>           token: ${{ secrets.DIAWI_TOKEN }}
>           file: ${{ steps.download.outputs.download-path }}/app-release.apk
> ```
> 
> <img alt="Screenshot 2023-06-06 at 6 52 03 PM" width="1057" src="https://private-user-images.githubusercontent.com/84075780/243709020-883d2687-1c72-46da-a71f-2b800ed287e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExODgwNDEsIm5iZiI6MTcwMTE4Nzc0MSwicGF0aCI6Ii84NDA3NTc4MC8yNDM3MDkwMjAtODgzZDI2ODctMWM3Mi00NmRhLWE3MWYtMmI4MDBlZDI4N2UzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE2MDkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiNTM5YWFmMzg1YjQ5MWQwNjk1NDJlZTJmNTg1MmIzZGNiM2E2NzZiMDkyNzhhYzk4MWU2ZDc2Yzc1ZWQyZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1DNyx5F9PzfccZoEqRdVmb2hk8ReePKfyo6TeFn8dQg">

any updates regarding this @bhavinatharva
