### ISSUE TITLE
Failing Action: action-upload-diawi@v1.2.1

### ISSUE THREAD

**Issue by yardstick17** [rnkdsh/action-upload-diawi#23] opened 2022-11-08 07:10 UTC
Since today, it has started to fail with this error trace:

```bash
Run rnkdsh/action-upload-diawi@v1.2.1
Failed:  Error: Error: Request failed with status code 504
    at Diawi.execute (/home/runner/work/_actions/rnkdsh/action-upload-diawi/v1.2.1/diawi.js:65:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Error: Request failed with status code 504

```

**Comment by rnkdsh** [comment] 2023-05-26 11:02
I am unable to reproduce this issue. Please try the latest version to check whether it's still happening or not. Closing the issue.

**Closed by rnkdsh** 2023-05-26 11:02 UTC
